root: true

extends:
  - pegasus
  - pegasus/browser
  - pegasus/node
  - prettier

rules:
  no-warning-comments: off
  max-params:
    - error
    - 4

overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    extends:
      - pegasus/react
      - pegasus/typescript
    parserOptions:
      project: './tsconfig.eslint.json'

ignorePatterns:
  - '!.storybook'
