root: true

extends:
  - pegasus
  - pegasus/browser
  - pegasus/node

rules:
  no-warning-comments: off
  max-params:
    - error
    - 4

overrides:
  - files:
      - '**/*.ts'
    extends:
      - pegasus/typescript
      - plugin:prettier/recommended
    parserOptions:
      project: './tsconfig.json'

  - files:
      - '**/*.tsx'
    extends:
      - pegasus/typescript
      - pegasus/react
      - plugin:prettier/recommended
    parserOptions:
      project: './tsconfig.json'
