name: Tests

env:
  NODE_VERSION: 16

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: node --version
      - run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test
